version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80
      - 443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      SPRING_MAIL_HOST: ${SMTP_HOST}
      SPRING_MAIL_PORT: ${SMTP_PORT}
      SPRING_MAIL_USERNAME: ${SMTP_USERNAME}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
    expose:
      - 8080
  app:
    build:
      context: ./app
      dockerfile: ./app/Dockerfile
    expose:
      - 80
    environment:
      API_URL: http://api:8080

