spring:
  config:
    use-legacy-processing: true
  datasource:
    url: jdbc:sqlite:personal-website.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

com.ndogga.mail.recipient: me@ndogga.com
